### ISSUE TITLE
brew install faust --HEAD gives error, complains about configoscdynamic confighttpdynamic switches

### ISSUE THREAD

**Issue by cerkut** [tomoyanonymous/homebrew-faust#1]
brew install faust works fine, but 
brew install faust --HEAD gives the following error
----
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C build configall configoscdynamic confighttpdynamic BACKENDS=world.cmake
mkdir faustdir
cd faustdir && cmake -DOSCDYNAMIC=on ..
cd faustdir && cmake -DHTTPDYNAMIC=on ..
/bin/sh: cmake: command not found
make[1]: *** [configoscdynamic] Error 127
make[1]: *** Waiting for unfinished jobs....
/bin/sh: cmake: command not found
make[1]: *** [confighttpdynamic] Error 127
make: *** [world] Error 2

**Comment by tomoyanonymous** [comment]
Thank you for your report and sorry for my lazy update. recently faust's build system was moved from make to cmake. Thus build step is slightly changed. The latest information to build faust is in a wiki. <https://github.com/grame-cncm/faust/wiki>

I'll update this formula in a few days.

**Comment by cerkut** [comment]
Still getting the same error, I guess should stick to /usr/local/Cellar/faust/2.5.21...
Thanks.

**Comment by tomoyanonymous** [comment]
Hi sorry again. Really same error? Could you try to install after `brew unlink faust` ? In my environment, now it works with --HEAD.

**Comment by cerkut** [comment]
Ok, thanks on Mojave 10.14 all worked with fresh install
=> Summary
🍺  /usr/local/Cellar/faust/HEAD-8775166: 1,020 files, 83.5MB, built in 8 minutes 33 seconds
==> Caveats
==> cmake
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> llvm
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH run:
  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/usr/local/opt/llvm/lib"
  export CPPFLAGS="-I/usr/local/opt/llvm/include"

My problem was on High Sierra, I did a =brew unlink faust= but will try again. Closing the issue. Thanks.
